package keycloaklib

var translations = map[string]map[string]string{
	"en": {
		ErrInvalidKeycloakURL:                       "Invalid Keycloak URL",
		ErrKeycloakURLMustUseHTTPS:                  "Keycloak URL must use HTTPS for security",
		ErrUserNotFound:                             "User not found",
		ErrGroupNotFound:                            "Group not found",
		ErrConfigRequired:                           "config is required",
		ErrKeycloakURLRequired:                      "KEYCLOAK_URL variable is required",
		ErrKeycloakRealmRequired:                    "KEYCLOAK_REALM variable is required",
		ErrKeycloakClientIDRequired:                 "KEYCLOAK_CLIENT_ID variable is required",
		ErrKeycloakClientSecretRequired:             "KEYCLOAK_CLIENT_SECRET variable is required",
		ErrClientIDAndSecretRequired:                "client_id and client_secret are required for admin operations",
		ErrNoAccessToken:                            "no access token in response",
		ErrNoRefreshToken:                           "no refresh token available",
		ErrNoAccessTokenInRefresh:                   "no access token in refresh response",
		ErrTokenRefreshFailed:                       "token refresh failed: %w",
		ErrFailedToCreateRequest:                    "failed to create request: %w",
		ErrFailedToExecuteRequest:                   "failed to execute request: %w",
		ErrFailedToReadResponse:                     "failed to read response: %w",
		ErrFailedToGetToken:                         "failed to get token: %d %s",
		ErrFailedToRefreshToken:                     "failed to refresh token: %d %s",
		ErrFailedToParseToken:                       "failed to parse token response: %w",
		ErrFailedToMarshalUser:                      "failed to marshal user data: %w",
		ErrFailedToCreateUserRequest:                "failed to create user request: %w",
		ErrFailedToCreateUser:                       "failed to create user: %d %s",
		ErrNoLocationHeader:                         "no Location header in response",
		ErrInvalidLocationHeader:                    "invalid Location header",
		ErrFailedToGetUserRequest:                   "failed to create get user request: %w",
		ErrFailedToExecuteGetUser:                   "failed to execute get user request: %w",
		ErrFailedToGetUser:                          "failed to get user: %d %s",
		ErrFailedToDecodeUser:                       "failed to decode user response: %w",
		ErrFailedToDeleteUserRequest:                "failed to create delete user request: %w",
		ErrFailedToExecuteDeleteUser:                "failed to execute delete user request: %w",
		ErrFailedToDeleteUser:                       "failed to delete user: %d %s",
		ErrUsernamePasswordRequired:                 "username and password are required",
		ErrClientIDRequired:                         "client_id or other_client_id is required",
		ErrFailedToObtainLoginToken:                 "failed to obtain login token: status %d, body: %s",
		ErrFailedToCreateGetClientRequest:           "failed to create get client request: %w",
		ErrFailedToExecuteGetClient:                 "failed to execute get client request: %w",
		ErrFailedToGetClient:                        "failed to get client, status: %d, body: %s",
		ErrFailedToDecodeClients:                    "failed to decode clients: %w",
		ErrNoClientFound:                            "no client found with clientId: %s",
		ErrFailedToCreateGetClientRoleRequest:       "failed to create get client role request: %w",
		ErrFailedToExecuteGetClientRole:             "failed to execute get client role request: %w",
		ErrFailedToGetClientRole:                    "failed to get client role, status: %d, body: %s",
		ErrFailedToDecodeClientRole:                 "failed to decode client role: %w",
		ErrFailedToGetClientWrapper:                 "failed to get client: %w",
		ErrFailedToGetClientRoleWrapper:             "failed to get client role %s: %w",
		ErrFailedToMarshalClientRoles:               "failed to marshal client roles: %w",
		ErrFailedToCreateAddClientRolesRequest:      "failed to create add client roles request: %w",
		ErrFailedToExecuteAddClientRoles:            "failed to execute add client roles request: %w",
		ErrFailedToAddClientRoles:                   "failed to add client roles, status: %d, body: %s",
		ErrUsernameAndEmailRequired:                 "username and email are required",
		ErrUserIDRequired:                           "userID is required",
		ErrFailedToCreateResetPasswordEmailRequest:  "failed to create reset password email request: %w",
		ErrFailedToExecuteResetPasswordEmailRequest: "failed to execute reset password email request: %w",
		ErrFailedToTriggerPasswordResetEmail:        "failed to trigger password reset email: status %d, body %s",
		ErrUsernameRequired:                         "username is required",
		ErrNoUserFound:                              "no user found with username: %s",
		ErrMultipleUsersFound:                       "multiple users found with username: %s",
		ErrFailedToMarshal:                          "failed to marshal request body: %w",
		ErrRequestFailed:                            "request failed: status %d, body: %s",
		ErrFailedToAddRolesRollbackFailed:           "failed to add roles: %v; rollback failed: %v",
		ErrFailedToAddRolesUserDeleted:              "failed to add roles: %v; user deleted successfully",
		ErrSubjectRequired:                          "subject is required",
		ErrRedirectURIRequired:                      "redirect URI is required",
		ErrFailedToGetUserID:                        "failed to get user ID: %w",
		ErrFailedToObtainImpersonationToken:         "failed to obtain impersonation token: status %d, body: %s",
		ErrNoCookiesInResponse:                      "no cookies in impersonation response",
		ErrNoRedirectInResponse:                     "no redirect in authentication response: status %d",
		ErrFailedToParseLocation:                    "failed to parse location header: %w",
		ErrNoTokenInLocation:                        "no token parameters in location header",
		ErrFailedToParseTokenParams:                 "failed to parse token parameters: %w",
		ErrFailedToGenerateMagicLink:                "failed to generate magic link: status %d, body: %s",
	},
	"pt": {
		ErrInvalidKeycloakURL:                       "URL do Keycloak inválida",
		ErrKeycloakURLMustUseHTTPS:                  "URL do Keycloak deve usar HTTPS por segurança",
		ErrConfigRequired:                           "a configuração é obrigatória",
		ErrKeycloakURLRequired:                      "a variável KEYCLOAK_URL é obrigatória",
		ErrKeycloakRealmRequired:                    "a variável KEYCLOAK_REALM é obrigatória",
		ErrKeycloakClientIDRequired:                 "a variável KEYCLOAK_CLIENT_ID é obrigatória",
		ErrKeycloakClientSecretRequired:             "a variável KEYCLOAK_CLIENT_SECRET é obrigatória",
		ErrClientIDAndSecretRequired:                "client_id e client_secret são obrigatórios para operações administrativas",
		ErrNoAccessToken:                            "nenhum token de acesso na resposta",
		ErrNoRefreshToken:                           "nenhum token de atualização disponível",
		ErrNoAccessTokenInRefresh:                   "nenhum token de acesso na resposta de atualização",
		ErrTokenRefreshFailed:                       "falha na atualização do token: %w",
		ErrFailedToCreateRequest:                    "falha ao criar a solicitação: %w",
		ErrFailedToExecuteRequest:                   "falha ao executar a solicitação: %w",
		ErrFailedToReadResponse:                     "falha ao ler a resposta: %w",
		ErrFailedToGetToken:                         "falha ao obter o token: %d %s",
		ErrFailedToRefreshToken:                     "falha ao atualizar o token: %d %s",
		ErrFailedToParseToken:                       "falha ao analisar a resposta do token: %w",
		ErrFailedToMarshalUser:                      "falha ao serializar os dados do usuário: %w",
		ErrFailedToCreateUserRequest:                "falha ao criar a solicitação de usuário: %w",
		ErrFailedToCreateUser:                       "falha ao criar o usuário: %d %s",
		ErrNoLocationHeader:                         "nenhum cabeçalho Location na resposta",
		ErrInvalidLocationHeader:                    "cabeçalho Location inválido",
		ErrFailedToGetUserRequest:                   "falha ao criar a solicitação de obtenção de usuário: %w",
		ErrFailedToExecuteGetUser:                   "falha ao executar a solicitação de obtenção de usuário: %w",
		ErrFailedToGetUser:                          "falha ao obter o usuário: %d %s",
		ErrFailedToDecodeUser:                       "falha ao decodificar a resposta do usuário: %w",
		ErrFailedToDeleteUserRequest:                "falha ao criar a solicitação de exclusão de usuário: %w",
		ErrFailedToExecuteDeleteUser:                "falha ao executar a solicitação de exclusão de usuário: %w",
		ErrFailedToDeleteUser:                       "falha ao excluir o usuário: %d %s",
		ErrUsernamePasswordRequired:                 "nome de usuário e senha são obrigatórios",
		ErrClientIDRequired:                         "client_id ou other_client_id é obrigatório",
		ErrFailedToObtainLoginToken:                 "falha ao obter o token de login: status %d, corpo: %s",
		ErrFailedToCreateGetClientRequest:           "falha ao criar a solicitação de obtenção de cliente: %w",
		ErrFailedToExecuteGetClient:                 "falha ao executar a solicitação de obtenção de cliente: %w",
		ErrFailedToGetClient:                        "falha ao obter o cliente, status: %d, corpo: %s",
		ErrFailedToDecodeClients:                    "falha ao decodificar os clientes: %w",
		ErrNoClientFound:                            "nenhum cliente encontrado com clientId: %s",
		ErrFailedToCreateGetClientRoleRequest:       "falha ao criar a solicitação de obtenção de role do cliente: %w",
		ErrFailedToExecuteGetClientRole:             "falha ao executar a solicitação de obtenção de role do cliente: %w",
		ErrFailedToGetClientRole:                    "falha ao obter a role do cliente, status: %d, corpo: %s",
		ErrFailedToDecodeClientRole:                 "falha ao decodificar a role do cliente: %w",
		ErrFailedToGetClientWrapper:                 "falha ao obter o cliente: %w",
		ErrFailedToGetClientRoleWrapper:             "falha ao obter a role do cliente %s: %w",
		ErrFailedToMarshalClientRoles:               "falha ao serializar as roles do cliente: %w",
		ErrFailedToCreateAddClientRolesRequest:      "falha ao criar a solicitação de adição de roles do cliente: %w",
		ErrFailedToExecuteAddClientRoles:            "falha ao executar a solicitação de adição de roles do cliente: %w",
		ErrFailedToAddClientRoles:                   "falha ao adicionar as roles do cliente, status: %d, corpo: %s",
		ErrUsernameAndEmailRequired:                 "nome de usuário e e-mail são obrigatórios",
		ErrUserIDRequired:                           "userID é obrigatório",
		ErrFailedToCreateResetPasswordEmailRequest:  "falha ao criar a solicitação de e-mail de redefinição de senha: %w",
		ErrFailedToExecuteResetPasswordEmailRequest: "falha ao executar a solicitação de e-mail de redefinição de senha: %w",
		ErrFailedToTriggerPasswordResetEmail:        "falha ao disparar o e-mail de redefinição de senha: status %d, corpo %s",
		ErrUsernameRequired:                         "nome de usuário é obrigatório",
		ErrNoUserFound:                              "nenhum usuário encontrado com nome de usuário: %s",
		ErrMultipleUsersFound:                       "múltiplos usuários encontrados com nome de usuário: %s",
		ErrFailedToMarshal:                          "falha ao serializar o corpo da solicitação: %w",
		ErrRequestFailed:                            "falha na solicitação: status %d, corpo: %s",
		ErrFailedToAddRolesRollbackFailed:           "falha ao adicionar roles: %v; falha no rollback: %v",
		ErrFailedToAddRolesUserDeleted:              "falha ao adicionar roles: %v; usuário deletado com sucesso",
		ErrSubjectRequired:                          "subject é obrigatório",
		ErrRedirectURIRequired:                      "redirect URI é obrigatório",
		ErrFailedToGetUserID:                        "falha ao obter o ID do usuário: %w",
		ErrFailedToObtainImpersonationToken:         "falha ao obter o token de impersonation: status %d, corpo: %s",
		ErrNoCookiesInResponse:                      "nenhum cookie na resposta de impersonation",
		ErrNoRedirectInResponse:                     "nenhum redirect na resposta de autenticação: status %d",
		ErrFailedToParseLocation:                    "falha ao analisar o cabeçalho location: %w",
		ErrNoTokenInLocation:                        "nenhum parâmetro de token no cabeçalho location",
		ErrFailedToParseTokenParams:                 "falha ao analisar os parâmetros do token: %w",
		ErrFailedToGenerateMagicLink:                "falha ao gerar magic link: status %d, corpo: %s",
	},
}
